### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by zhangSaneC** [Thinklab-SJTU/Bench2Drive#100]
Would you please show more examples or introdutions about how to visualize results?

For example, how to use tools/visualize.py, like how to show all info. including Lidar, 6 views cameras, BEV,... in one video?

Thanks for your reply.

**Comment by jayyoung0802** [comment]
Hi @zhangSaneC, The role of tools/visualize.py is how to use this data and visualization, just run it.

**Comment by zhangSaneC** [comment]
Thanks for your quick reply.

To my understand, the --map_path is e.g., Bench2DriveZoo/data/bench2drive/maps/Town01_HD_map.npz, right?

May I ask what is the setting of --file_path?
