### ISSUE TITLE
Wrong steer in Datasets？

### ISSUE THREAD

**Issue by Lzc6996** [Thinklab-SJTU/Bench2Drive#102]
Issue Description
I have noticed inconsistencies in the steer values while using the dataset. Here are some specific cases I observed:
1. In the file CrossingBicycleFlow_Town12_Route1063_Weather23/anno/00343.json.gz, the agent is turning, but the steer value is 0.
2. In the file CrossingBicycleFlow_Town12_Route862_Weather3/anno/00342.json.gz, the agent's steer value is -0.5, but in 00343 it changes to -0.1, and then jumps back a few frames later.
This phenomenon seems to be prevalent throughout the dataset. Could this be an issue with the data itself, or am I misunderstanding something in my usage?

Thank you for your help!

**Comment by jayyoung0802** [comment]
Turning is a process, steer is an instantaneous value. Since the action space of the RL agent is discrete, the actions are not smooth. You can watch our [demo](https://www.youtube.com/watch?v=-osdzJJs2g0) to feel this process.
