### ISSUE TITLE
 No module named 'uniad_b2d_agent'

### ISSUE THREAD

**Issue by JokerWhy233** [Thinklab-SJTU/Bench2Drive#103]
我在运行 bash leaderboard/scripts/run_evaluation_debug.sh时 ， 报 No module named 'uniad_b2d_agent' ， 我的参数如下：TEAM_AGENT=Bench2DriveZoo/leaderboard/team_code/uniad_b2d_agent.py
TEAM_CONFIG=Bench2DriveZoo/adzoo/uniad/configs/stage2_e2e/base_e2e_b2d.py
是哪里出错了吗？ 
同时还出现了Disabling core dumps

**Comment by jayyoung0802** [comment]
You should create a soft link according to this guide [EVAL_IN_CARLA](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/EVAL_IN_CARLA.md).

**Comment by wlll123456** [comment]
运行 bash leaderboard/scripts/run_evaluation_debug.sh，显示段错误(Segmentation fault)，请问具体参数要怎么设置

**Comment by jayyoung0802** [comment]
Hi @wlll123456 Please check whether `vulkaninfo` is running properly (apt install vulkan-tools), and then check carla follow [this](https://github.com/Thinklab-SJTU/Bench2Drive/issues/37#issuecomment-2259593146).

**Comment by wlll123456** [comment]
![image](https://github.com/user-attachments/assets/e0d16235-6b8c-4688-9399-24862b6ea326)
![image](https://github.com/user-attachments/assets/8cf119a0-4af2-4e83-b671-96cd9f7aeb66)
![image](https://github.com/user-attachments/assets/68d08689-681b-43ee-bec1-7bda22bc692c)
第一张是正常运行carla，会显示disabling core dumps; 第二张vulkan也会显示； 第三张是命令运行，显示段错误

**Comment by wlll123456** [comment]
我用的是bench2drive数据集，是不是与bench2drive220.xml不匹配导致的？

**Comment by jayyoung0802** [comment]
<img width="578" alt="image" src="https://github.com/user-attachments/assets/6bb991ee-3e96-4da5-a6b9-d3eaff72190c">
This warning needs to be resolved.
