### ISSUE TITLE
Evaluation without sensor data recording

### ISSUE THREAD

**Issue by dikshant2210** [Thinklab-SJTU/Bench2Drive#104]
Hello, is it possible to stop the sensor data logging when running the eval pipeline. I am trying to reproduce the results in the paper. So far, I have been able to run the eval on a single GPU which is quite slow and I would like to expedite it therefore I wanted to stop recording sensor data to disk but couldn't figure out how to do it.

**Comment by dikshant2210** [comment]
Thank you for the answer, I was able to run it without logging sensor data. I am running it on 2 GPU setup with one for Carla and one for running the model, but its still quite slow, it took roughly 14 hours for 16 scenarios (16 out of 220), is this to be expected or there is some problem?

**Comment by jayyoung0802** [comment]
You can check the average time for each step in output logger.  
Below is a rough estimate of each algorithm in the closed loop, (in H800)
- UniAD--1.4s
- VAD--1.1s
- TCP--0.4s
