### ISSUE TITLE
how to generate leaderboard/data/bench2drive220.xml file

### ISSUE THREAD

**Issue by xuarehere** [Thinklab-SJTU/Bench2Drive#105]
Your work is fantastic. Thank you for your open source.

If I want to difine the  custom route, what should I do?
how to generate the opensscenario file , like  leaderboard/data/bench2drive220.xml.

**Comment by jiaxiaosong1002** [comment]
@xuarehere It is generated by our in-house Think2Drive code.   You could always manually define new route by checking the code of scenariorunner

**Comment by wlll123456** [comment]
我在使用mini数据集测试，手动修改xml文件，但是发现一些场景没有找到对应的xml内容.还有，我发现代码里的配置文件中类别数与uniad原本不一致，是不是不能使用原来的权重测试？

**Comment by Kin-Zhang** [comment]
Same question here, I also want to know how the bench2drive.xml file be genereated, I would say [scneariorunner](https://scenario-runner.readthedocs.io/en/latest/creating_new_scenario/#adding-the-scenario-configuration) is not in the bench2drive case.

Could you provide more detail on this question?

**Comment by jingzhengli** [comment]
> Same question here, I also want to know how the bench2drive.xml file be genereated, I would say [scneariorunner](https://scenario-runner.readthedocs.io/en/latest/creating_new_scenario/#adding-the-scenario-configuration) is not in the bench2drive case.
> 
> Could you provide more detail on this question?

same question..
