### ISSUE TITLE
About closed-loop evaluation

### ISSUE THREAD

**Issue by robosuite** [Thinklab-SJTU/Bench2Drive#106]
Hi authors! Great work and thanks for making it open-source! Can you provide some more detailed instructions on how to run the baseline model for closed-loop evaluation? (for example VAD). Any reference would be appreciated to run it on one gpu (A100 for example) and on headless mode.

**Comment by jiaxiaosong1002** [comment]
@robosuite See Bench2DriveZoo: https://github.com/Thinklab-SJTU/Bench2DriveZoo
