### ISSUE TITLE
ques about traffic signs ability

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#107]
hello, I am a little confused about the calculation process of the traffic signs ability in ability_benchmark.py, could you please give a brief explanation？ Thanks

**Comment by starlighttt123** [comment]
besides, the code shows that each route in the traffic sign seems to be calculated twice?

**Comment by Random8756** [comment]
Here is a brief explanation: For routes that include traffic signs (stop signs or traffic lights), we first calculate the position of the trigger volume, and then calculate the route completion value that would be achieved if the ego vehicle travels from the starting location to this location. If the ego vehicle's route completion is greater than this value and no stop sign infraction or running red light infraction is triggered, then it is considered that the ego vehicle has the ability to pass through traffic signs in that evaluation. Each route will be calculated only once.
