### ISSUE TITLE
No module named 'agents.navigation.constant_velocity_agent'

### ISSUE THREAD

**Issue by Eden-Wang1710** [Thinklab-SJTU/Bench2Drive#108]
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 31, in <module>
    from leaderboard.scenarios.route_scenario import RouteScenario
  File "/root/paddlejob/workspace/env_run/Bench2Drive/leaderboard/leaderboard/scenarios/route_scenario.py", line 29, in <module>
    from srunner.scenariomanager.scenarioatomics.atomic_behaviors import ScenarioTriggerer, Idle
  File "/root/paddlejob/workspace/env_run/Bench2Drive/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py", line 33, in <module>
    from agents.navigation.constant_velocity_agent import ConstantVelocityAgent

ModuleNotFoundError: No module named 'agents.navigation.constant_velocity_agent'

Seems that no such file in this dictionary:
<img width="294" alt="截屏2024-10-11 17 52 17" src="https://github.com/user-attachments/assets/15030185-b917-4b12-a8a2-528305c6c692">

**Comment by jayyoung0802** [comment]
Hi, follow this, https://github.com/Thinklab-SJTU/Bench2Drive/issues/90#issuecomment-2339645174

**Comment by Eden-Wang1710** [comment]
> Hi, follow this [#90 (comment)](https://github.com/Thinklab-SJTU/Bench2Drive/issues/90#issuecomment-2339645174)

Thanks for your reply, I have set the CARLA path. 
However, there's no such `constant_velocity_agent` file in the repo.

**Comment by jayyoung0802** [comment]
Carla version is 0.9.15.
<img width="515" alt="image" src="https://github.com/user-attachments/assets/c1810eb2-7166-4aaf-b5d7-15bdba49641c">
