### ISSUE TITLE
Question about cmd

### ISSUE THREAD

**Issue by YiHuang108** [Thinklab-SJTU/Bench2Drive#109]
While reviewing the code, I noticed that commands are generated alongside GPS data during the loading process. However, in CARLA, the presence of other interfering vehicles may affect the agent's path. If the agent continues to follow the previously generated commands despite interference, this could result in the "Agent deviated from the route" error. 

Since model test is seriously affected by this problem. Do you have any plans to address this issue? Looking forward to your replay.

**Comment by jayyoung0802** [comment]
Hi, this is a different concept. Current behavior is a real-time decision. Autonomous driving  agents require a route or command(which derived from route) to tell them where to go.

**Comment by YiHuang108** [comment]
In my actual test results, the model turns right when it interacts with another vehicle, or the model predicts that the route will change to straight immediately after the right turn. Is this irrelevant to the command?

**Comment by jiaxiaosong1002** [comment]
@YiHuang108 Please check the team_code agent to understand the command system.
