### ISSUE TITLE
Fetching 0 files: 0it [00:00, ?it/s] in mini dataset.

### ISSUE THREAD

**Issue by synsin0** [Thinklab-SJTU/Bench2Drive#11]
I try to download mini dataset with huggingface or hf-mirror, both receives no file, maybe a change of data root?

**Comment by jiaxiaosong1002** [comment]
@synsin0  Considering using huggingface mirror: https://hf-mirror.com/.

**Comment by synsin0** [comment]
I tried this mirror and also fetch 0 files in the dataset. I choose to download from baiduyun.

**Comment by EricLiuhhh** [comment]
I faced the same problem. In my case, it can be solved by adding ".tar.gz" to the ``--include`` parameter, e.g., ``huggingface-cli download --resume-download --repo-type dataset rethinklab/Bench2Drive --include "HardBreakRoute_Town01_Route30_Weather3.tar.gz" --local-dir Bench2Drive-mini``
