### ISSUE TITLE
The number of pedestrians used to test in BASE Dataset

### ISSUE THREAD

**Issue by Mr-Fu620** [Thinklab-SJTU/Bench2Drive#110]
I found that under the BASE dataset, the number of **pedestrians** in the tested dataset is particularly small, only more than 500, is this normal？

**Comment by jiaxiaosong1002** [comment]
@Mr-Fu620  Indeed, pedestrian is rare in CARLA.  In fact, the validation set is carefully selected to make sure there is at least one instance per class to avoid collapsing the detection code since there are rarer types like truck.
