### ISSUE TITLE
Is it possible to perform closed-loop evaluation in headless mode?

### ISSUE THREAD

**Issue by WhateverItTakes07** [Thinklab-SJTU/Bench2Drive#111]
Is it possible to perform closed-loop evaluation in headless mode? I ran the evaluation on the A800 server and encountered the following problem.
![image](https://github.com/user-attachments/assets/a4b4aeb0-34c1-4af5-9a73-d465d162c574)

**Comment by jayyoung0802** [comment]
Hi, if you use A800, your system must be ubuntu 22. And install some packages, such as 
`
apt install vulkan-tools 
` 
`
apt install libgeos-dev
`
