### ISSUE TITLE
ques about key in Ability in ability_bench2mark.py

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#112]
hello, I have some questions about the Ability dict in ability_bench2mark.py:
1. Firsitly, "VanillaNonSignalizedTurnEncounterStopsign" seems to be written wrongly to "VanillaNonSignalizedTurnEncouterStopsign", which might influence the output metrics.
2. "ParkingCrossingPedestrian" and "MergerIntoSlowTraffic"  can't be found in Ability dict,  which is a catagory in test data.

**Comment by jiaxiaosong1002** [comment]
@starlighttt123 Great point! Thanks a lot for your kind advice.  We will re-evaluate the results and upload them soon.

**Comment by jiaxiaosong1002** [comment]
@starlighttt123 Please check the latest update. Thanks again for your suggestion!
