### ISSUE TITLE
List of filenames

### ISSUE THREAD

**Issue by stars79689** [Thinklab-SJTU/Bench2Drive#115]
Could you please offer a list of filenames(ie, AccidentTwoWays_Town12_Route20977_Weather20.tar.gz AccidentTwoWays_Town12_Route20978_Weather21.tar.gz AccidentTwoWays_Town12_Route20979_Weather22.tar.gz AccidentTwoWays_Town12_Route20981_Weather23.tar.gz AccidentTwoWays_Town12_Route20984_Weather1.tar.gz) for full dataset(4T)

**Comment by jayyoung0802** [comment]
Hi @stars79689, please refer to [docs](https://github.com/Thinklab-SJTU/Bench2Drive/tree/main/docs).
