### ISSUE TITLE
Traffic flow does not follow traffic rules

### ISSUE THREAD

**Issue by Kiki2049** [Thinklab-SJTU/Bench2Drive#116]
Thank you for your great work!

I was running some scenarios and noticed that the traffic flow was not obeying the rules of the road and since the cars were staying for long periods of time.
For example, in RouteScenario_2201_rep0, the traffic flow runs a red light. I would like to know if this is an error in running my simulator or a problem with the scenario.

Looking forward to your reply！

**Comment by Kiki2049** [comment]
Sorry I didn't read the appendix carefully before, I've solved my problem

**Comment by Kiki2049** [comment]
A flow of cars runs a red light in front of the ego when it enters the junction, forcing it to react (interrupting the flow or merging into the flow). These vehicles are ’special’ ones such as police cars, ambulances, or firetrucks.

Sorry, I still have some confusion. You mentioned that these are special vehicles, so what is the optimal behavior for ego vehicle? Are there any successful examples? 
If its target point is across the street, then it interrupts traffic. But this doesn't seem very reasonable either.

**Comment by jiaxiaosong1002** [comment]
@Kiki2049 Please check supplymental of Bench2Drive paper and CARLA Leaderboard 2.0 docs https://leaderboard.carla.org/scenarios/
