### ISSUE TITLE
Validation pkl file is much larger than the training

### ISSUE THREAD

**Issue by ymoghadd** [Thinklab-SJTU/Bench2Drive#117]
Hi,

I noticed that the validation pkl file (b2d_infos_val.pkl) that's generated is much larger than the training (b2d_infos_train.pkl). Why is this?

**Comment by zhiyuanzzz** [comment]
`b2d_infos_train.pkl` (about 2.21GB) should be much larger than `b2d_infos_val.pkl` (about 135MB). Please check that you download the complete dataset and the preparation code runs successfully.
