### ISSUE TITLE
Using source-compiled carla

### ISSUE THREAD

**Issue by Ian-Tam** [Thinklab-SJTU/Bench2Drive#118]
Thanks for your contributions. I want to make some changes to the environment in Carla to test the robustness of the end-to-end model, currently compiled Carla through source (not the installed pre-compiled package), how can I establish a connection with the Carla simulator.

**Comment by jayyoung0802** [comment]
Hi @Ian-Tam, you should  set your `.egg` into the PYTHONPATH and `import carla` correctly.
