### ISSUE TITLE
how to remove autopilot other actors in routes of this codebase?

### ISSUE THREAD

**Issue by iuhiyuh** [Thinklab-SJTU/Bench2Drive#120]
In route_scenario, there are some static agents that can be removed, but I can’t find where to remove the dynamic agents.

**Comment by jayyoung0802** [comment]
Hi @iuhiyuh, the static agents are defined in [background_activity](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/scenario_runner/srunner/scenarios/background_activity.py), you can try to remove it if you need.  Of course, we haven't tried it

**Comment by iuhiyuh** [comment]
Looks like that’s it，thanks for the quick response!
