### ISSUE TITLE
why does the location.z of ego_vehicle turn to a negative?

### ISSUE THREAD

**Issue by xuyanhai2004** [Thinklab-SJTU/Bench2Drive#121]
When run the run_evaluation_debug.sh, the location.z of ego_vehicle turns to a negative after 20 seconds.  In fact, the altitude of the given scenario is about 380 meters.

BTW, the action of ego_vehicle is correct when the procedure runs. But when use another machine, the results was wrong as mentioned before. the location.z is wrong.

Thanks.

**Comment by jayyoung0802** [comment]
Please make sure the coordinate system(left-hand, ego, world, gps, etc.) for comparison is consistent.
