### ISSUE TITLE
The problem about visualization of vehicle trajectory

### ISSUE THREAD

**Issue by Mr-Fu620** [Thinklab-SJTU/Bench2Drive#122]
Excellent work！ I trying to visualize the trajectories I get from the VAD, this trajectory doesn't seem normal，and when I projected the track onto the front camera image , it wasn't normal either. Is there code to project the car's trajectory into the front view？
![image](https://github.com/user-attachments/assets/f0920acf-286f-4b06-b486-ab4b7b1bd4c4)

**Comment by jiaxiaosong1002** [comment]
@Mr-Fu620 Not sure about the issue. You should know that the performance of all modules of UniAD and VAD is far from perfect, which requires future endeavor of the community.

**Comment by Mr-Fu620** [comment]
Thank you for your reply！But this is the trajectory drawn from GT，It refers to the method of obtaining the trajectory from self.get_ego_trajs in B2D_vad_dataset.py

**Comment by jiaxiaosong1002** [comment]
@Mr-Fu620 Your Figure is unclear.  When conducting visualization, we suggest 1. set the axis of x and y as equal and the scale should not be too small.  For example, due to the noise of CARLA sensors, even for stationary vehicle, its future trajectories could have tiny fluctuation.
