### ISSUE TITLE
IS_BENCH2DRIVE is not set correctly in run_evaluation.sh

### ISSUE THREAD

**Issue by Kait0** [Thinklab-SJTU/Bench2Drive#124]
The == should be a = in run_evaluation.sh
https://github.com/Thinklab-SJTU/Bench2Drive/blob/8f9f1da103ea7153a17c5b1dd046548a9bcd5af2/leaderboard/scripts/run_evaluation.sh#L20

**Comment by jiaxiaosong1002** [comment]
@Kait0 Hi, thanks for pointing out the error! Indeed, it is a typo and we will fix it. This flag would not influence the performance of models.
