### ISSUE TITLE
你好，请问怎么在场景中添加车辆和行人

### ISSUE THREAD

**Issue by shuiyihang** [Thinklab-SJTU/Bench2Drive#126]
我在使用`bash leaderboard/scripts/run_evaluation_multi_uniad_tiny.sh`命令测试Uniad。
希望设计场景，改变其中的车辆和行人数量，我看了下代码
似乎是有两处的：
1. 在`bench2drive220_0_uniad_tiny_traj.xml`中添加`other_actor`标签，但是这种方法位置该怎么确定呢，加入位置不准确会有什么影响吗
2. 在`BackgroundBehavior`类中存在`_initialise_road_behavior`方法，可以批量在自车前后增加车辆，但是这种方式可能不是我需要的。
请问我该怎么处理或者有什么参考吗，谢谢！

**Comment by jayyoung0802** [comment]
We have not done any relevant exploration. Maybe you can calculate a specific position and then spawn an actor.

**Comment by shuiyihang** [comment]
> We have not done any relevant exploration. Maybe you can calculate a specific position and then spawn an actor.

thank you~

**Comment by Ian-Tam** [comment]
@shuiyihang 你好，请问下你实现这种功能了吗
