### ISSUE TITLE
查看一张图片中检测到的实例数量

### ISSUE THREAD

**Issue by shuiyihang** [Thinklab-SJTU/Bench2Drive#127]
你好，我想要查看下一轮循环，图片中track模块检测到的实例数量，
我注意到uniad_track.py中的
out["track_instances_fordet"] = track_instances         #这两个应该关系着目标数量
out["track_instances"] = out_track_instances 
但是当我打印出这两个值来看数量非常大，都在900以上，
请问的我的方式有问题嘛

**Comment by zhiyuanzzz** [comment]
@shuiyihang  We strictly follow UniAD's official code for training. You may read the related code for the meaning of these variables.
