### ISSUE TITLE
请问怎么知道当前车辆所拍摄路段的车道线坐标

### ISSUE THREAD

**Issue by xiaobh1519** [Thinklab-SJTU/Bench2Drive#129]
您好，请问怎么将车道线坐标和当前车辆位置关联起来呢

**Comment by jayyoung0802** [comment]
Hi @xiaobh1519, you can refer to [visualize.py](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/tools/visualize.py), and get the way how to use.
