### ISSUE TITLE
How to train model with your data

### ISSUE THREAD

**Issue by zhanghui75** [Thinklab-SJTU/Bench2Drive#14]
I want to train my planning model with your dataset (e.g. 1000 clips from BaiduYun). I have two questions:
1. do you have standard train/val split on this 1000 clips?
2. could you open some dataset class (e.g. nuScenes tool set) for the model to read your data?

**Comment by jayyoung0802** [comment]
Hi, thanks for your attention. 
1. The standard train/val split,  [bench2drive_base_train_val_split.json](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/data/splits/bench2drive_base_train_val_split.json).
2. We provide a visualize tool,  just enjoy it [visualize tool](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/tools/visualize.py).
