### ISSUE TITLE
Where is TownXX_lanemarkings.npz?

### ISSUE THREAD

**Issue by EricLiuhhh** [Thinklab-SJTU/Bench2Drive#15]
Thanks for your excellent work! I have downloaded HD-Map files, but I can't find ``maps/TownXX_lanemarkings.npz`` mentioned in ``visualize.py``. I'm sorry if I missed any details.

**Comment by jayyoung0802** [comment]
Hi, you can download it from [Bench2Drive-Map](https://huggingface.co/datasets/rethinklab/Bench2Drive-Map/tree/main).
We rename TownXX_lanemarkings.npz to Townxx_HD_map.npz for more standard naming.

**Comment by EricLiuhhh** [comment]
Hi! But when I use Townxx_HD_map.npz in ``visualize.py``, I got the error below
![image](https://github.com/Thinklab-SJTU/Bench2Drive/assets/128712481/19e8de7e-8592-4af7-91a7-b83c43b60845)
![image](https://github.com/Thinklab-SJTU/Bench2Drive/assets/128712481/5ec8cae0-9263-4c72-97af-db1f2c7145e2)

Is there some changes between lanemarkings.npz and HD_map.npz?

**Comment by jayyoung0802** [comment]
Hi,  we fix the visualize code,  please pull the latest branch and try it. And the HD-Map details can be found in [HD-Map Data Structure](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/docs/anno.md).
Thank you for finding the problem！

**Comment by EricLiuhhh** [comment]
It works, thx!
