### ISSUE TITLE
no module named 'mmcv._ext'

### ISSUE THREAD

**Issue by StevenJ308** [Thinklab-SJTU/Bench2Drive#16]
Hi, I'm reporting error no module named 'mmcv._ext' when I want to try to do a closed loop evaluation, the top level of this error is **line 121** in **leaderboard_evaluator.py**, _self.module_agent = importlib.import_module( module_name)_. I don't know why it jumps to **line 11** in **mmcv/utils/ext_loader.py** and reports an error. As I understand it, your code already integrates with mmcv, do I need to download and compile the mmcv source again?

**Comment by jiaxiaosong1002** [comment]
@StevenJ308 It seems that the compiled operator does not work.  Are there any errors during the installation of environment?  Are the environment variables set correctly? 

Note that the original mmcv is not required. The  [installation process](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md) should be **strictly** followed.
