### ISSUE TITLE
The downloaded Bench2Drive-Full dataset is only 2.7T != 4T, it will be 4T after decompression?

### ISSUE THREAD

**Issue by AvinsWang** [Thinklab-SJTU/Bench2Drive#17]
I downloaded the Bench2Drive-Full dataset, but I noticed a discrepancy in the size. The downloaded dataset is 2.7TB, whereas the expected size is 4TB. However, the number of files (9371) matches the expected count.

Could this size difference be due to compression, and will the dataset expand to 4TB upon extraction? To ensure data integrity, could you please provide an MD5 checksum list for the files? This will allow me to verify that all files have been downloaded correctly.

**Comment by jiaxiaosong1002** [comment]
@AvinsWang Hi, thanks for your interests. Currently, we are conducting a further cleaning and extending process on the full set. Thus, the final file size might be estimated incorrectly. You may run with the current 9371 + 1000 files. We will publish a notification when the cleaning process finished.  Please stay tuned.

**Comment by AvinsWang** [comment]
Thanks! I'll use the current data and look forward to the good news, btw, when will you finish the cleaning process

**Comment by AvinsWang** [comment]
@jiaxiaosong1002 Thanks! I'll use the current data and look forward to the good news, btw, when will you finish the cleaning process

**Comment by jiaxiaosong1002** [comment]
@AvinsWang Hi, you may check the latest version of full set.

**Comment by AvinsWang** [comment]
@jiaxiaosong1002 Thanks, I have downloaded it.
