### ISSUE TITLE
command's meaning

### ISSUE THREAD

**Issue by xiaobh1519** [Thinklab-SJTU/Bench2Drive#19]
![image](https://github.com/Thinklab-SJTU/Bench2Drive/assets/79265019/8d8121b7-bad5-4144-bfac-391ca50a9877)
Hi! I noticed that your command has six types (1 to 6). Could you please explain what each number represents?

**Comment by jiaxiaosong1002** [comment]
@xiaobh1519 https://github.com/Thinklab-SJTU/Bench2Drive/issues/9
