### ISSUE TITLE
Closed-loop evaluation resume 

### ISSUE THREAD

**Issue by StevenJ308** [Thinklab-SJTU/Bench2Drive#20]
Hi, thanks for making the code public, I'm having some problems reproducing the closed loop eval. Since I am single gpu, I am using the debug mode directly for the evaluation, but every time I can't run through 220 routes and crahsed. when I reevaluate it, it will start the evaluation from the beginning. I see that **_resume=True_** has been set in the shell script, why would it still start from the beginning? What should I do to avoid evaluating routes that have already been evaluated? Thank you very much!

**Comment by jayyoung0802** [comment]
**_resume=True_** works well. It uses the json file to determine the route id of the evaluation, please keep the file path unchanged. And if one route always crashed(may be caused by agent behavior), you can skip it and 'progress'-1 manually.

**Comment by StevenJ308** [comment]
Thank you very much for your answer. I looked at the code again and realized that in the _**while loop**_ of the **_validate_and_resume_** function, it checks the **_status_** of the tested route, and my json file shows that the **_status_** of the initial route is **_Failed_**, which leads to restarting the test every time～
