### ISSUE TITLE
How to use anno['theta']?

### ISSUE THREAD

**Issue by weimengchuan** [Thinklab-SJTU/Bench2Drive#22]
Hi, What is the definition of anno['theta'], and how to use it?

Thanks in advance!

**Comment by jayyoung0802** [comment]
The orientation of vehicle, which in radians and North is (0.0, -1.0, 0.0) in UE Coordinate System.
For more details, please refer to the introduction of [compass](https://carla.readthedocs.io/en/latest/ref_sensors/#imu-sensor) in the official documentation of carla.
