### ISSUE TITLE
Question about GT bboxes of VehicleOpenDoor.

### ISSUE THREAD

**Issue by weimengchuan** [Thinklab-SJTU/Bench2Drive#29]
Hi, I find the GT bboxes of VehicleOpenDoor only includes the body of the car, not the open door.

Example:
VehicleOpensDoorTwoWays/VehicleOpensDoorTwoWays_Town12_Route1203_Weather7/camera/rgb_front_3d_bbox/00055.jpg

Sorry, I am unable to upload images due to network issues.

Thanks in advance!

**Comment by jiaxiaosong1002** [comment]
@weimengchuan  Good point! Unfortunately, CARLA API does not consider the door open scenario and thus the box is incomplete.  

BTW, I think this issue should be handled either by E2E Learning or Occupancy, as one of the challenging perception corner case.
