### ISSUE TITLE
Dissappearing vehicles during evaluation

### ISSUE THREAD

**Issue by itsbman** [Thinklab-SJTU/Bench2Drive#31]
I'm running `run_evaluation_debug.sh` with the provided VAD model and I observe that occasionally a surrounding vehicle dissappear. Here is an example showing consecutive frames in `RouteScenario_1792_rep0_Town12_HazardAtSideLane_1_18_07_18_10_50_03`

<img src="https://github.com/user-attachments/assets/f97e5e34-8bf4-4929-a384-1604c7dde783 " width="256" height="256">
<img src="https://github.com/user-attachments/assets/fe689fd7-ff51-4096-8bbf-09aa73ffc899" width="256" height="256">

Is this a problem of scenario runner?
I want to know what could possibly cause this or if it will influence the results.

Thanks in advance

**Comment by jiaxiaosong1002** [comment]
@itsbman Hi, it is the behavior of CARLA to clean those vehicles unrelated to scenarios. It is normal. We agree that it is unnatural and may need some update in the future by the CARLA team.
