### ISSUE TITLE
Eval时报错Segmentation fault

### ISSUE THREAD

**Issue by jacken3** [Thinklab-SJTU/Bench2Drive#32]
试图复现uniAD闭环仿真评测的结果时出现如下报错：

bash leaderboard/scripts/run_evaluation_debug.sh
/data/carla/CarlaUE4.sh -RenderOffScreen -nosound -carla-rpc-port=30000 -graphicsadapter=3 None
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
load_world failed , attempts=0
time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30000
load_world success , attempts=1
traffic_manager init success, try_time=0

========= Preparing RouteScenario_1773 (repetition 0) =========
> Loading the world
> Setting up the agent
/data/projects/Bench2DriveZoo/mmcv/models/modules/custom_base_transformer_layer.py:77: UserWarning: The arguments `feedforward_channels` in BaseTransformerLayer has been deprecated, now you should set `feedforward_channels` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/data/projects/Bench2DriveZoo/mmcv/models/modules/custom_base_transformer_layer.py:77: UserWarning: The arguments `ffn_dropout` in BaseTransformerLayer has been deprecated, now you should set `ffn_drop` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/data/projects/Bench2DriveZoo/mmcv/models/modules/custom_base_transformer_layer.py:77: UserWarning: The arguments `ffn_num_fcs` in BaseTransformerLayer has been deprecated, now you should set `num_fcs` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/data/projects/Bench2DriveZoo/mmcv/models/bricks/transformer.py:353: UserWarning: The arguments `feedforward_channels` in BaseTransformerLayer has been deprecated, now you should set `feedforward_channels` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/data/projects/Bench2DriveZoo/mmcv/models/bricks/transformer.py:353: UserWarning: The arguments `ffn_dropout` in BaseTransformerLayer has been deprecated, now you should set `ffn_drop` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/data/projects/Bench2DriveZoo/mmcv/models/bricks/transformer.py:353: UserWarning: The arguments `ffn_num_fcs` in BaseTransformerLayer has been deprecated, now you should set `num_fcs` and other FFN related arguments to a dict named `ffn_cfgs`. 
  warnings.warn(
/data/projects/Bench2DriveZoo/mmcv/models/bricks/transformer.py:96: UserWarning: The arguments `dropout` in MultiheadAttention has been deprecated, now you can separately set `attn_drop`(float), proj_drop(float), and `dropout_layer`(dict) 
  warnings.warn('The arguments `dropout` in MultiheadAttention '
load checkpoint from path: ckpts/uniad_base_b2d.pth
2024-07-18 14:34:50,461 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.0.conv2 is upgraded to version 2.
2024-07-18 14:34:50,469 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.1.conv2 is upgraded to version 2.
2024-07-18 14:34:50,474 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.2.conv2 is upgraded to version 2.
2024-07-18 14:34:50,480 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.3.conv2 is upgraded to version 2.
2024-07-18 14:34:50,524 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.4.conv2 is upgraded to version 2.
2024-07-18 14:34:50,530 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.5.conv2 is upgraded to version 2.
2024-07-18 14:34:50,535 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.6.conv2 is upgraded to version 2.
2024-07-18 14:34:50,541 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.7.conv2 is upgraded to version 2.
2024-07-18 14:34:50,546 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.8.conv2 is upgraded to version 2.
2024-07-18 14:34:50,551 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.9.conv2 is upgraded to version 2.
2024-07-18 14:34:50,556 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.10.conv2 is upgraded to version 2.
2024-07-18 14:34:50,562 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.11.conv2 is upgraded to version 2.
2024-07-18 14:34:50,567 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.12.conv2 is upgraded to version 2.
2024-07-18 14:34:50,572 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.13.conv2 is upgraded to version 2.
2024-07-18 14:34:50,577 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.14.conv2 is upgraded to version 2.
2024-07-18 14:34:50,620 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.15.conv2 is upgraded to version 2.
2024-07-18 14:34:50,625 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.16.conv2 is upgraded to version 2.
2024-07-18 14:34:50,631 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.17.conv2 is upgraded to version 2.
2024-07-18 14:34:50,636 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.18.conv2 is upgraded to version 2.
2024-07-18 14:34:50,641 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.19.conv2 is upgraded to version 2.
2024-07-18 14:34:50,647 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.20.conv2 is upgraded to version 2.
2024-07-18 14:34:50,652 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.21.conv2 is upgraded to version 2.
2024-07-18 14:34:50,657 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.22.conv2 is upgraded to version 2.
2024-07-18 14:34:50,663 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.0.conv2 is upgraded to version 2.
2024-07-18 14:34:50,670 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.1.conv2 is upgraded to version 2.
2024-07-18 14:34:50,676 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.2.conv2 is upgraded to version 2.
> Running the route
Segmentation fault

看起来carla的server正常启动了，agent也成功加载了，但是不知道为什么在 Running the route缓解出现了Segmentation fault的错误

**Comment by jayyoung0802** [comment]
"WARNING: lavapipe is not a conformant vulkan implementation, testing use only."

carla并没有正常启动，在linux 命令行试试 vulkaninfo | grep Version，查看是否显示正常，并正确安装vulkaninfo， sudo apt install vulkan-utils.

验证carla是否正常启动，进入carla目录，输入命令行 ./CarlaUE4.sh -RenderOffScreen -nosound -fps=10 -carla-rpc-port=2000

**Comment by jacken3** [comment]
运行vulkaninfo | grep Version

输出：
'DISPLAY' environment variable not set... skipping surface info
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Vulkan Instance Version: 1.2.131
        apiVersion     = 4198582 (1.1.182)
        driverVersion  = 1 (0x0001)
        conformanceVersion = 1.0.0.0
        
好像确实不太正常
下面是显卡驱动信息：
Thu Jul 18 14:56:48 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:4F:00.0 Off |                  N/A |
| 30%   26C    P8    25W / 350W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:52:00.0 Off |                  N/A |
| 30%   25C    P8    21W / 350W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:56:00.0 Off |                  N/A |
| 30%   25C    P8    24W / 350W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:D5:00.0 Off |                  N/A |
| 30%   27C    P8    26W / 350W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+  
麻烦问一下有什么建议嘛

**Comment by jayyoung0802** [comment]
安装以及更新一下vulkaninfo
驱动的话，这个版本是可用的（NVIDIA-SMI 515.65.01   Driver Version: 515.65.01）

**Comment by martinchen0776** [comment]
./CarlaUE4.sh -RenderOffScreen -nosound -fps=10 -carla-rpc-port=2000 启动报错

4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
LowLevelFatalError [File:Unknown] [Line: 1214] 
GameThread timed out waiting for RenderThread after 60.00 secs
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault

驱动版本
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:9D:00.0 Off |                    0 |
| 30%   33C    P8    24W / 300W |      0MiB / 46080MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:A0:00.0 Off |                    0 |
| 30%   35C    P8    33W / 300W |      0MiB / 46080MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
vulkaninfo已安装
'DISPLAY' environment variable not set... skipping surface info
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Vulkan Instance Version: 1.2.131
        apiVersion     = 4198582 (1.1.182)
        driverVersion  = 1 (0x0001)
        conformanceVersion = 1.0.0.0

看起来是驱动没对上吗？求帮忙

**Comment by aaa1233211** [comment]
你好，请教下运行./CarlaUE4.sh -RenderOffScreen -nosound -fps=10 -carla-rpc-port=2000出现下面的报错，可以帮忙看下吗，感激不尽。
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
LowLevelFatalError [File:Unknown] [Line: 136] 
Exception thrown: bind: Address already in use
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault

**Comment by jayyoung0802** [comment]
Hi @aaa1233211, Port is already in use. Please run [clean.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/tools/clean_carla.sh) to clean the carla's remaining process.

**Comment by aaa1233211** [comment]
> Hi @aaa1233211, Port is already in use. Please run [clean.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/tools/clean_carla.sh) to clean the carla's remaining process.

Thanks, I tried, but also occur this error.

4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
LowLevelFatalError [File:Unknown] [Line: 1214] 
GameThread timed out waiting for RenderThread after 60.00 secs
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault

**Comment by jayyoung0802** [comment]
A800 need ubuntu22.04, and latest vulkan-tools.

**Comment by aaa1233211** [comment]
> A800 need ubuntu22.04, and latest vulkan-tools.

是ubuntu22.04以及最新的vulkan-tools，但是还是不行，请教下有可能是由于在服务器上运行的原因吗，主机上可以正常运行，但是服务器上一跑就挂

**Comment by likelyzhao** [comment]
> > A800 need ubuntu22.04, and latest vulkan-tools.
> 
> 是ubuntu22.04以及最新的vulkan-tools，但是还是不行，请教下有可能是由于在服务器上运行的原因吗，主机上可以正常运行，但是服务器上一跑就挂

你好，请问您这个问题找到解决方案了吗，我遇到了一样的问题

**Comment by Kxin1226** [comment]
> A800 need ubuntu22.04, and latest vulkan-tools.

I also encounter this problem, and can you give some solid solutions to solve this problem?
I use 8 A800 machine, and the latest vulkan. Still cannot finish the multi_uniad task successfully.

**Comment by jayyoung0802** [comment]
Hi @aaa1233211, @Kxin1226, and @likelyzhao, another way is use the official Docker image.
```
docker pull carlasim/carla:0.9.15
```
And customize the image on your machine. We have already tested and it works well.
