### ISSUE TITLE
Failed when run evaluation

### ISSUE THREAD

**Issue by donkehuang** [Thinklab-SJTU/Bench2Drive#33]
Hi, thans for your great work and effort. I have trouble when run the evaluation of VAD and here are the command i used and error info.
![image](https://github.com/user-attachments/assets/7a551c51-393f-475f-ad07-825f411ba2fb)
`bash leaderboard/scripts/run_evaluation_debug.sh

`

when i run the carla seperately, it works and shows the figure like this 
![image](https://github.com/user-attachments/assets/c4467a96-be66-4b1f-a82e-f2f4a78ed3e7)

And my evaluation config is like this, are these config right for VAD evaluation?
`#!/bin/bash
BASE_PORT=30000
BASE_TM_PORT=50000
IS_BENCH2DRIVE=True
BASE_ROUTES=leaderboard/data/bench2drive220
TEAM_AGENT=leaderboard/team_code/vad_b2d_agent.py
TEAM_CONFIG=~/Bench2Drive/Bench2DriveZoo/ckpts/vad_b2d_base.pth # for UniAD and VAD
BASE_CHECKPOINT_ENDPOINT=eval
SAVE_PATH=~/Bench2DriveZoo/test/
PLANNER_TYPE=only_traj

GPU_RANK=3
PORT=$BASE_PORT
TM_PORT=$BASE_TM_PORT
ROUTES="${BASE_ROUTES}.xml"
CHECKPOINT_ENDPOINT="${BASE_CHECKPOINT_ENDPOINT}.json"
bash leaderboard/scripts/run_evaluation.sh $PORT $TM_PORT $IS_BENCH2DRIVE $ROUTES $TEAM_AGENT $TEAM_CONFIG $CHECKPOINT_ENDPOINT $SAVE_PATH $PLANNER_TYPE $GPU_RANK
`

Thanks a lot!

**Comment by jayyoung0802** [comment]
It seems that there is a problem with the carla version. Please check the carla version(0.9.15).

**Comment by Amireux52** [comment]
> Hi, thans for your great work and effort. I have trouble when run the evaluation of VAD and here are the command i used and error info. ![image](https://github.com/user-attachments/assets/7a551c51-393f-475f-ad07-825f411ba2fb) `bash leaderboard/scripts/run_evaluation_debug.sh
> 
> `
> 
> when i run the carla seperately, it works and shows the figure like this ![image](https://github.com/user-attachments/assets/c4467a96-be66-4b1f-a82e-f2f4a78ed3e7)
> 
> And my evaluation config is like this, are these config right for VAD evaluation? `#!/bin/bash BASE_PORT=30000 BASE_TM_PORT=50000 IS_BENCH2DRIVE=True BASE_ROUTES=leaderboard/data/bench2drive220 TEAM_AGENT=leaderboard/team_code/vad_b2d_agent.py TEAM_CONFIG=~/Bench2Drive/Bench2DriveZoo/ckpts/vad_b2d_base.pth # for UniAD and VAD BASE_CHECKPOINT_ENDPOINT=eval SAVE_PATH=~/Bench2DriveZoo/test/ PLANNER_TYPE=only_traj
> 
> GPU_RANK=3 PORT=$BASE_PORT TM_PORT=$BASE_TM_PORT ROUTES="${BASE_ROUTES}.xml" CHECKPOINT_ENDPOINT="${BASE_CHECKPOINT_ENDPOINT}.json" bash leaderboard/scripts/run_evaluation.sh $PORT $TM_PORT $IS_BENCH2DRIVE $ROUTES $TEAM_AGENT $TEAM_CONFIG $CHECKPOINT_ENDPOINT $SAVE_PATH $PLANNER_TYPE $GPU_RANK `
> 
> Thanks a lot!

hi, did you sovle it? how to get it, thank you
