### ISSUE TITLE
map

### ISSUE THREAD

**Issue by xiaobh1519** [Thinklab-SJTU/Bench2Drive#34]
Hello, thank you for your great work. I have a question I would like to ask. 

In the generated `b2d_map_infos.pkl`, I noticed that the x or y coordinates of the `lane_pts` are very large, mostly around 300, whereas in NuScenes, the `lane_pts` are mostly in the range of 0 to 50. Therefore, I would like to ask where the origin of the Bench2Drive coordinates is and why there is such a huge difference.

**Comment by jiaxiaosong1002** [comment]
@xiaobh1519  Hi, we use CARLA official API to sample from the CARLA official maps. Thus, users are free to generate customized density by using CARLA themselves without replying on experts.

We save high density maps to make sure people who need this level of density could have it.
