### ISSUE TITLE
A bug for extrinsic?

### ISSUE THREAD

**Issue by swc-17** [Thinklab-SJTU/Bench2Drive#36]
I think the lidar2cam for CAM_BACK is not normal [here](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/31432e868c3ca1bef5c7fa39ba4bd4e7a3e7538a/team_code/vad_b2d_agent.py#L120), could you please double-check it?

**Comment by jiaxiaosong1002** [comment]
@swc-17 Good point. Thanks for pointing out! It is a bug during evaluation. We are glad to hear from you about the influence of correct extrinsics.

BTW, it should be
'CAM_BACK':np.array([[-5.60166031e+02, -8.00000000e+02,  0.00000000e+00, -1.28800000e+03],
                     [ 5.51091060e-14, -4.50000000e+02, -5.60166031e+02, -8.58939847e+02],
                     [ 1.22464680e-16, -1.00000000e+00,  0.00000000e+00, -1.61000000e+00],
                     [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

**Comment by wjl2244** [comment]
> @swc-17 Good point. Thanks for pointing out! It is a bug during evaluation. We are glad to hear from you about the influence of correct extrinsics.
> 
> BTW, it should be 'CAM_BACK':np.array([[-5.60166031e+02, -8.00000000e+02,  0.00000000e+00, -1.28800000e+03],                      [ 5.51091060e-14, -4.50000000e+02, -5.60166031e+02, -8.58939847e+02],                      [ 1.22464680e-16, -1.00000000e+00,  0.00000000e+00, -1.61000000e+00],                      [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

So why not update the correct extrinsics in the branch UniAD/VAD?
