### ISSUE TITLE
why repetition？

### ISSUE THREAD

**Issue by chuanye-Wang** [Thinklab-SJTU/Bench2Drive#39]
![image](https://github.com/user-attachments/assets/badc9872-802b-471f-822e-f4090dea2ac9)
Realized that the "repitition" value means to repeat the simlation for routes several turns. why we do that?

**Comment by jiaxiaosong1002** [comment]
@chuanye-Wang It's set as 1, which means we do not do it in Bench2Drive.  If you run regular CARLA routes, it is suggested to adopt multiple runs due to its high variance.

**Comment by chuanye-Wang** [comment]
Got it, thank you so much.
