### ISSUE TITLE
ThinkTwice & DriveAdapter Reproduction

### ISSUE THREAD

**Issue by ryhnhao** [Thinklab-SJTU/Bench2Drive#4]
Hi,
Great and meaningful work on closed-loop benchmarking! 

Now (Jun. 11th, 2024), the repo seems to have 4 methods released (AD-MLP & TCP & UniAD & VAD :)
I wonder when ThinkTwice & DriveAdapter will be released.
Do you have a schedule?

Thanks a lot, and look forward to your reply!

**Comment by jiaxiaosong1002** [comment]
@ryhnhao Hi, since ThinkTwice & DriveAdapter requires expert feature at every layer, we do not intend to open source Think2Drive related code recently. Thanks

**Comment by ryhnhao** [comment]
@jiaxiaosong1002 
Hi, thanks for your in-time reply.

I also notice that the paper claimed that TCP also employs expert feature. (As "_As a result, methods (TCP/ThinkTwice/DriveAdapter) with expert feature distillation outperforms those without (VAD/UniAD) by a large margin._")

I wonder what's the difference between the expert feature of ThinkTwice&DriveAdapter and that of TCP?
And why they are chosen different?
To the best of your knowledge, are there other expert feature alternatives available for carla-v2 (apart from your great work Think2Drive)

Thanks a lot, and look forward to your reply!

And BTW, good luck to your papers :)

**Comment by jiaxiaosong1002** [comment]
@ryhnhao Thanks!

**We try our best to strictly follow the official implementation of each baseline.**  In TCP,  it only uses 1D  expert features as it does not involve any BEV transformation. We release the 1D expert feature in the Bench2Drive dataset (expert_assessment subfolder).   In ThinkTwice and DriveAdapter, they use every layer of expert feature including both 1D feature and BEV feature.

I am not aware of any other expert with feature. However, there is a good open-sourced rule-based expert (https://github.com/autonomousvision/carla_garage/tree/leaderboard_2)  if you need an expert.

**Comment by ryhnhao** [comment]
@jiaxiaosong1002 
Thank you very much.
I don't have further issues.
