### ISSUE TITLE
simulation rate 

### ISSUE THREAD

**Issue by wyield** [Thinklab-SJTU/Bench2Drive#40]
When running run_evaluation_debug.sh,I find that the simulation rate is very slow, probably around 0.05x. The current GPU used is 3090.How to improve it？
![2024-08-02](https://github.com/user-attachments/assets/5187f876-d4c7-47b7-864e-c7fa39cfe5bd)

**Comment by jiaxiaosong1002** [comment]
@wyield  CARLA is inherently slow and E2E models like UniAD and VAD are huge as well. Thus, the only way is to use multiple GPUs to conduct evaluation in parallel.

**Comment by wyield** [comment]
I see~~ Thanks a lot. :)

**Comment by wyield** [comment]
BTW，How about turning off camera data saving inside the code, will it work when it's off?

**Comment by jiaxiaosong1002** [comment]
@wyield save_data function could be commented if there is no need to visualization.

**Comment by wyield** [comment]
I tried it and it won't help speed up the simulation rate, thanks for the help anyway!
