### ISSUE TITLE
hello，Can you provide an example？

### ISSUE THREAD

**Issue by scuizhibin** [Thinklab-SJTU/Bench2Drive#45]

**Comment by jayyoung0802** [comment]
Hi, thanks for your question, please provide more details so that we can better assist you.

**Comment by scuizhibin** [comment]
给一个测试模型的例子，官方只给了一个说明。


---Original---
From: ***@***.***&gt;
Date: Wed, Aug 7, 2024 11:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] hello，Can you provide an example？ (Issue #45)




 
Hi, thanks for your question, please provide more details so that we can better assist you.
 
&mdash;

**Comment by jayyoung0802** [comment]
The model and ckpt in [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo),  the eval tutorial is in [EVAL_IN_CARLA](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/EVAL_IN_CARLA.md)

**Comment by scuizhibin** [comment]
echo&nbsp;&quot;$CARLA_ROOT/PythonAPI/carla/dist/carla-0.9.15-py3.7-linux-x86_64.egg&quot;&nbsp;&gt;&gt;&nbsp;YOUR_CONDA_PATH/envs/YOUR_CONDA_ENV_NAME/lib/python3.7/site-packages/carla.pth&nbsp;&nbsp;&nbsp;这个conda环境指的是哪一个？并没有详细说明


---Original---
From: ***@***.***&gt;
Date: Wed, Aug 7, 2024 14:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] hello，Can you provide an example？ (Issue #45)




 
The model and ckpt in Bench2DriveZoo,  the eval tutorial is in EVAL_IN_CARLA
 
&mdash;

**Comment by scuizhibin** [comment]
请问torch的版本是多少，按照readme的安装是2.4.0。pip&nbsp;install&nbsp;e.会出现问题。


---Original---
From: ***@***.***&gt;
Date: Wed, Aug 7, 2024 14:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] hello，Can you provide an example？ (Issue #45)




 
The model and ckpt in Bench2DriveZoo,  the eval tutorial is in EVAL_IN_CARLA
 
&mdash;

**Comment by jayyoung0802** [comment]
Support latest torch,  the install tutorial is in [INSTALL](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md)
