### ISSUE TITLE
Can't open file tools/split_xml.py

### ISSUE THREAD

**Issue by Reezzz702** [Thinklab-SJTU/Bench2Drive#5]
Hi, appreciate of your amazing work. 

I tried to run parallel evaluation with [leaderboard/scripts/run_evaluation_multi.sh](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation_multi.sh), however, the error message showed that tools/split_xml.py do not exist, I also checked the code base and do not find it as well. I wonder if I missed something when cloning the repo?

**Comment by jayyoung0802** [comment]
Thanks for your question, updated

**Comment by Reezzz702** [comment]
Thanks for your quick reply and update!
