### ISSUE TITLE
How to create own data using data_collect.py No main()

### ISSUE THREAD

**Issue by fsong666** [Thinklab-SJTU/Bench2Drive#50]
How to create own data using data_collect.py? Are there any examples？Many thanks

**Comment by fsong666** [comment]
How to create own data using data_collect.py? Are there any examples？Many thanks

**Comment by jiaxiaosong1002** [comment]
@fsong666 You may use the expert from https://github.com/autonomousvision/carla_garage/tree/leaderboard_2.  However, we are not sure whether they are enough to solve all scenes.

**We suggest only use the official data of Bench2Drive for fair comparison.**

**Comment by fsong666** [comment]
> @fsong666 You may use the expert from https://github.com/autonomousvision/carla_garage/tree/leaderboard_2. However, we are not sure whether they are enough to solve all scenes.
> 
> **We suggest only use the official data of Bench2Drive for fair comparison.**
Many thanks. 
Did you use this code https://github.com/autonomousvision/carla_garage/tree/leaderboard_2  to generate your data?

**Comment by fsong666** [comment]
Many thanks.
I mean, that data_collect.py has no main() to create data. Could you provide such main() or scripts to create own data, whose format is same as yours.

**Comment by jiaxiaosong1002** [comment]
@fsong666 The data collection code is merely for the understanding of the collection process so that users could better process the dataset. You may write your own code to collect your own data.
