### ISSUE TITLE
ModuleNotFoundError: No module named 'agents.navigation.constant_velocity_agent'

### ISSUE THREAD

**Issue by ChipsICU** [Thinklab-SJTU/Bench2Drive#51]
Hello guys:

I’ve encountered a curious issue while evaluating the vad_b2d_agent. When running the evaluation, I’m met with the following error:

`
ModuleNotFoundError: No module named 'agents.navigation.constant_velocity_agent'
`

It seems that this module is supposed to be part of the CARLA Simulator, as it is referenced in the file Bench2Drive/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py. However, despite having CARLA properly installed and imported, this particular module appears to be elusive.

In a moment of curiosity and desperation, I decided to comment out the line and it works:

`
from agents.navigation.constant_velocity_agent import ConstantVelocityAgent
`

**Is this import necessary**?  Will its absence cause problems down the line?

**Comment by jiaxiaosong1002** [comment]
@ChipsICU No problem. You could comment out it.

**Comment by ChipsICU** [comment]
> @ChipsICU No problem. You could comment out it.
Actually, for the **opposite_vehicle_taking_priority** and **yield_to_emergency_vehicle scenarios**, agents.navigation.constant_velocity_agent is used, if commented out this line, the program will crash when the code runs to these scenes.
