### ISSUE TITLE
from agents.navigation.global_route_planner import GlobalRoutePlanner

### ISSUE THREAD

**Issue by scuizhibin** [Thinklab-SJTU/Bench2Drive#52]
我按照readme上的要求进行安装carla,运行bash leaderboard/scripts/run_evaluation_debug.sh，出现问题

**Comment by AvinsWang** [comment]
我之前也遇到过, 添加下面两行解决了 
```
import sys
sys.path.append('/path_to_carla/PythonAPI/carla')
```

**Comment by scuizhibin** [comment]
> @scuizhibin 我之前也遇到过, 添加下面两行解决了
> 
> ```
> import sys
> sys.path.append('/path_to_carla/PythonAPI/carla')
> ```

还有一个问题 如果把VAD跑起来，run_evaluation_debug.sh  中TEAM_CONFIG如何设置？

**Comment by AvinsWang** [comment]
@scuizhibin 和你使用ckpt对应即可, 我使用的是 Bench2DriveZoo/ckpts/uniad_tiny_b2d.pth
```shell
TEAM_CONFIG=Bench2DriveZoo/adzoo/uniad/configs/stage2_e2e/tiny_e2e_b2d.py
```
这样设置加载checkpoint可能出现问题, 可以手动修改下Bench2DriveZoo/team_code/vad_b2d_agent.py
```python
self.ckpt_path = 'Bench2DriveZoo/ckpts/uniad_tiny_b2d.pth'
checkpoint = load_checkpoint(self.model, self.ckpt_path, map_location='cpu', strict=True)
```

**Comment by scuizhibin** [comment]
> @scuizhibin 和你使用ckpt对应即可, 我使用的是 Bench2DriveZoo/ckpts/uniad_tiny_b2d.pth
> 
> ```shell
> TEAM_CONFIG=Bench2DriveZoo/adzoo/uniad/configs/stage2_e2e/tiny_e2e_b2d.py
> ```
> 
> 这样设置加载checkpoint可能出现问题, 可以手动修改下Bench2DriveZoo/team_code/vad_b2d_agent.py
> 
> ```python
> self.ckpt_path = 'Bench2DriveZoo/ckpts/uniad_tiny_b2d.pth'
> checkpoint = load_checkpoint(self.model, self.ckpt_path, map_location='cpu', strict=True)
> ``` 
最后一个问题  我的torch版本是2.4，torchvision 版本0.19.0，但是运行bash命令出现，RuntimeError: operator torchvision::nms does not exist

**Comment by AvinsWang** [comment]
@scuizhibin 这是我使用的版本, 按照[INSTALL.md](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md)安装能成功运行;你的问题我没遇到过, 不知道怎么解, 可以重装下INSTALL.md或者按照官方重新配置环境
> torch                     2.4.0+cu118
torchaudio                2.4.0+cu118
torchmetrics              0.11.4
torchvision               0.19.0+cu118

**Comment by scuizhibin** [comment]
> @scuizhibin 这是我使用的版本, 按照[INSTALL.md](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md)安装能成功运行;你的问题我没遇到过, 不知道怎么解, 可以重装下torchvision或者按照官方重新配置环境
> 
> > torch                     2.4.0+cu118
> > torchaudio                2.4.0+cu118
> > torchmetrics              0.11.4
> > torchvision               0.19.0+cu118

ATen/native/TensorShape.cpp:3587.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
--- anchor_info_path  /home/zzx/CZB/Bench2DriveZoo/data/others/b2d_motion_anchor_infos_mode6.pkl
load checkpoint from path: /media/zzx/data/workspace/Bench2Drive-base/uniad_tiny_b2d.pth
> Running the route
=== [Agent] -- Wallclock = 2024-08-14 09:21:34.430 -- System time = 0.000 -- Game time = 0.050 -- Ratio = 0.000x
/home/zzx/.local/lib/python3.8/site-packages/scipy/optimize/_minpack_py.py:178: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
leaderboard/scripts/run_evaluation.sh：行 44: 21984 段错误               （核心已转储） CUDA_VISIBLE_DEVICES=${GPU_RANK} python ${LEADERBOARD_ROOT}/leaderboard/leaderboard_evaluator.py --routes=${ROUTES} --repetitions=${REPETITI=${CHALLENGE_TRACK_CODENAME} --checkpoint=${CHECKPOINT_ENDPOINT} --agent=${TEAM_AGENT} --agent-config=${TEAM_CONFIG} --debug=${DEBUG_CHALLENGE} --record=${RECORD_PATH} --resume=${RESUME} --port=${PORT} --traffic-manager-port=${TM_PORT} --gpu-rank=${GPU_RANK}这个问题是显存不足吗？还是其他原因

**Comment by AvinsWang** [comment]
@scuizhibin 从上面信息不确定是哪一步出错了, 你可以调试代码看下具体发生在哪. 3060(notebook) 8G报OOM错误(uniad_tiny), 换成 A100 实际占用显存约9.4G(VAD);

**Comment by scuizhibin** [comment]
这个问题你遇到没有



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 13, 2024 15:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] fromagents.navigation.global_route_planner import GlobalRoutePlanner (Issue #52)




 
@scuizhibin 这是我使用的版本, 按照INSTALL.md安装能成功运行;你的问题我没遇到过, 不知道怎么解, 可以重装下INSTALL.md或者按照官方重新配置环境
  
torch                     2.4.0+cu118
 torchaudio                2.4.0+cu118
 torchmetrics              0.11.4
 torchvision               0.19.0+cu118

**Comment by happytianhao** [comment]
> 我按照readme上的要求进行安装carla,运行bash leaderboard/scripts/run_evaluation_debug.sh，出现问题

在Bench2Drive/leaderboard/scripts/run_evaluation.sh中设置一下CARLA_ROOT~

**Comment by JesseTowne** [comment]
> @scuizhibin 这是我使用的版本, 按照[INSTALL.md](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md)安装能成功运行;你的问题我没遇到过, 不知道怎么解, 可以重装下torchvision或者按照官方重新配置环境
> 
> > torch                     2.4.0+cu118
> > torchaudio                2.4.0+cu118
> > torchmetrics              0.11.4
> > torchvision               0.19.0+cu118

请问在CUDA 11.8的条件下，如何配置VAD的虚拟环境？我发现[INSTALL.md](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md)并未提及VAD所需的MMCV、MMDetection、MMDetection3D等依赖库的版本号

**Comment by JesseTowne** [comment]
> @scuizhibin 这是我使用的版本, 按照[INSTALL.md](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md)安装能成功运行;你的问题我没遇到过, 不知道怎么解, 可以重装下torchvision或者按照官方重新配置环境
> 
> > torch                     2.4.0+cu118
> > torchaudio                2.4.0+cu118
> > torchmetrics              0.11.4
> > torchvision               0.19.0+cu118

@AvinsWang @scuizhibin 请问在CUDA 11.8的条件下，如何配置VAD的虚拟环境？我发现[INSTALL.md](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/INSTALL.md)并未提及VAD所需的MMCV、MMDetection、MMDetection3D等依赖库的版本号

**Comment by jayyoung0802** [comment]
Hi, @JesseTowne. You do not need another repo(MMCV、MMDetection、MMDetection3D) anymore,  just follow step 6, `pip install -v -e .`
