### ISSUE TITLE
Bench2Drive-Full和Bench2Drive-Full-Sup数据存在文件名重复, 应该使用哪里面的数据?

### ISSUE THREAD

**Issue by AvinsWang** [Thinklab-SJTU/Bench2Drive#53]
在处理数据时发现Bench2Drive-Full和Bench2Drive-Full-Sup存在同名, Bench2Drive-Full:9881, Bench2Drive-Full-Sup: 3813, 其中同名的数据有56个, 总数为9881+3813-56=13638; 文件名重复的软链接并不一样, 重复的文件应该使用Full里的还是Full-Sup里面的?
[diff.txt](https://github.com/user-attachments/files/16596076/diff.txt)

**Comment by jayyoung0802** [comment]
是相同的，保留其中一个即可。（相同route id都是同一个）这是由于文件名命名更改TJunction/T_Junction导致的

**Comment by AvinsWang** [comment]
@jayyoung0802 
所有文件我都使用sha256校验了, 如果文件一致它们的sha256应该相同; 现在是文件内容完全一样, 因为某些原因导致sha256不同是吗

**Comment by jayyoung0802** [comment]
对，本地改了文件名，分别压缩目录后的sha256就不同了

**Comment by AvinsWang** [comment]
明白了, 多谢解答
