### ISSUE TITLE
显存要求是多少的？这个工程

### ISSUE THREAD

**Issue by scuizhibin** [Thinklab-SJTU/Bench2Drive#54]

**Comment by jayyoung0802** [comment]
uniad/vad是8卡A100(80G)训练的，TCP/ADMLP 4090/3090 可以训练

**Comment by happytianhao** [comment]
请问一下，uniad和vad的训练时间和训练资源是怎样滴谢谢~

**Comment by jiaxiaosong1002** [comment]
@happytianhao For training, BEVFormer + UniAD - 8 * A100 * 2 weeks.   VAD - 8 * A100 * 5 days.

**Comment by scuizhibin** [comment]
电脑内存128g够吗？


---原始邮件---
发件人: &quot;Xiaosong ***@***.***&gt;
发送时间: 2024年8月19日(周一) 凌晨0:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Thinklab-SJTU/Bench2Drive] 显存要求是多少的？这个工程 (Issue #54)




 
@happytianhao For training, BEVFormer + UniAD - 8 * A100 * 2 weeks.   VAD - 8 * A100 * 5 days.
 
&mdash;
