### ISSUE TITLE
验证集数据不存在

### ISSUE THREAD

**Issue by AvinsWang** [Thinklab-SJTU/Bench2Drive#55]
使用过程中发现[bench2drive_base_train_val_split.json](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/data/splits/bench2drive_base_train_val_split.json )文件中提供的验证集在13638clips不存在, 请问这是什么原因, 应该用哪些数据做验证集?

**Comment by jayyoung0802** [comment]
13638clips是full的，[bench2drive_base_train_val_split.json](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/data/splits/bench2drive_base_train_val_split.json) 这是是base（1000clip）的，如果全量训的话，训练就full+base, 测试就是base的val

**Comment by AvinsWang** [comment]
@jayyoung0802 我在base（1000clip）检查了一下, 还是没有发现这50个clip, 可以给一下base的文件列表吗; 训练集full+base 一个有多少个clip, 也可以给一个文件列表吗

**Comment by jayyoung0802** [comment]
huggingface上是有的，[Base 文件列表](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/docs/bench2drive_base_1000.json)
