### ISSUE TITLE
Base dataset download link invaild 

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#56]
![20240814-155737](https://github.com/user-attachments/assets/1858fd78-42f0-4af5-bd33-d52757f9288b)
hello,thanks for your incredible work, but the link seems to be invaild, can you please update the dataset download link

**Comment by jiaxiaosong1002** [comment]
@starlighttt123  Thanks for your kind advice. There is a missing k in the rethinklab. Will fix it.
