### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#58]
when running :
bash leaderboard/scripts/run_evaluation_multi.sh
A bug has occurred:
ImportError: /home/user/Bench2DriveZoo/mmcv/_[ext.cpython-38-x86_64-linux-gnu.so](http://ext.cpython-38-x86_64-linux-gnu.so/): undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv

it seems to be a problem of gcc version confilct with mmcv？could you tell me your version of gcc, Or other possible reasons of this bug, thanks.

**Comment by jayyoung0802** [comment]
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
