### ISSUE TITLE
运行uniad例子，出现failed to open libnvrtc-builtins.so.11.8.这个问题有遇到过的吗？

### ISSUE THREAD

**Issue by scuizhibin** [Thinklab-SJTU/Bench2Drive#59]

**Comment by jayyoung0802** [comment]
感觉还是环境哪里装的不对。
pip show torch -----> 2.4.0+cu118 (一定得有cu118)

**Comment by scuizhibin** [comment]
换了驱动，暂时问题没了，换成另一个问题。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 晚上7:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Thinklab-SJTU/Bench2Drive] 运行uniad例子，出现failed to open libnvrtc-builtins.so.11.8.这个问题有遇到过的吗？ (Issue #59)




 
感觉还是环境哪里装的不对。
 pip show torch -----&gt; 2.4.0+cu118 (一定得有cu118)
 
&mdash;

**Comment by scuizhibin** [comment]
ptx_box&nbsp;这个问题。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 晚上7:14
收件人: ***@***.******@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: 回复：[Thinklab-SJTU/Bench2Drive] 运行uniad例子，出现failed to open libnvrtc-builtins.so.11.8.这个问题有遇到过的吗？ (Issue #59)


换了驱动，暂时问题没了，换成另一个问题。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 晚上7:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Thinklab-SJTU/Bench2Drive] 运行uniad例子，出现failed to open libnvrtc-builtins.so.11.8.这个问题有遇到过的吗？ (Issue #59)




 
感觉还是环境哪里装的不对。
 pip show torch -----&gt; 2.4.0+cu118 (一定得有cu118)
 
&mdash;

**Comment by jayyoung0802** [comment]
看不到问题，截个图看看？

**Comment by scuizhibin** [comment]
![P20240815-090950](https://github.com/user-attachments/assets/cd0a4289-ca2f-4d5e-9e1d-20987445124f)

**Comment by scuizhibin** [comment]
> 看不到问题，截个图看看？这个属于正常运行吗？
![Uploading P20240815-090950.jpg…]()

**Comment by scuizhibin** [comment]
> 看不到问题，截个图看看？这个属于正常运行吗？
![P20240815-090950](https://github.com/user-attachments/assets/cf2bd041-1728-4ae9-a377-a01b9829c27d)

**Comment by jayyoung0802** [comment]
已经正常跑起来了

**Comment by scuizhibin** [comment]
跑了5个小时的代码，出现了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月15日(周四) 中午12:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Thinklab-SJTU/Bench2Drive] 运行uniad例子，出现failed to open libnvrtc-builtins.so.11.8.这个问题有遇到过的吗？ (Issue #59)




 
已经正常跑起来了
