### ISSUE TITLE
about dataset downloading.

### ISSUE THREAD

**Issue by zhanghui75** [Thinklab-SJTU/Bench2Drive#6]
For the dataset, could you kindly provide some link at baidu yun, which is more convenient for domestic users? Thanks a lot!

**Comment by MWPony** [comment]
@jiaxiaosong1002 Hi, how to solve the problem of "connection reused" when downloading mini datasets?
![image](https://github.com/Thinklab-SJTU/Bench2Drive/assets/115352662/ec7452e9-9094-408f-9b22-9d34f9455b51)

**Comment by jayyoung0802** [comment]
The mini download script is for huggingface official website, not domestic mirror huggingface. Try to see if you can access the huggingface official website normally. If not, please fix your network problem first.
