### ISSUE TITLE
How do I assign a different GPU to each closed-loop evaluated CARLA simulator?

### ISSUE THREAD

**Issue by wjl2244** [Thinklab-SJTU/Bench2Drive#63]
Hello, I am unable to specify the GPU device on which the CARLA emulator runs during parallel closed-loop evaluations. My CARLA version is 0.9.15, and I am using an `8×A800` device. However, CARLA only runs on GPU-3. I have set `CUDA_VISIBLE_DEVICES`, but it does not work.

**Comment by jiaxiaosong1002** [comment]
@wjl2244 You should also specify the CARLA about which GPU to use by -graphicsadapter=.

https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/leaderboard/leaderboard_evaluator.py#L203

**Comment by wjl2244** [comment]
> 您还应该通过 -graphicsadapter= 指定关于使用哪个 GPU 的 CARLA。
> 
> https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/leaderboard/leaderboard_evaluator.py#L203

Thank you for your reply, but it still doesn't work. Is there any other way to set it？
