### ISSUE TITLE
Can you provide a list of scenarios where uniad, vad, and tcp fail?

### ISSUE THREAD

**Issue by ChipsICU** [Thinklab-SJTU/Bench2Drive#64]
Can you provide a list of scenarios where uniad, vad, and tcp fail? Reproducing scenarios where these methods fail is time-consuming. Thank your very much!

**Comment by jiaxiaosong1002** [comment]
@ChipsICU We provide the eval jsons of the latest version Bench2Drive in Bench2DriveZoo.
