### ISSUE TITLE
leaderboard_evaluator.py: error: argument --gpu-rank: invalid int value: ''

### ISSUE THREAD

**Issue by scuizhibin** [Thinklab-SJTU/Bench2Drive#66]
当我使用bash leaderboard/scripts/run_evaluation_multi.sh  ，出现这个问题。

**Comment by jayyoung0802** [comment]
这个原因是由于没有设置planner_type导致。我们更新了代码，进一步完善了run_evaluation_multi.sh，请pull一下最新代码再尝试。
