### ISSUE TITLE
A few confusion about data_collect.py ＆ Dataset

### ISSUE THREAD

**Issue by hollowknight2167** [Thinklab-SJTU/Bench2Drive#67]
Hello, my esteemed authors. Recently, I'm work on the dataset you have provided and I'd like to ask you some question.

When I make a attempt to use the Semantic LIDAR data following the **data_collect.py**, I come to find that the data stored in the files : **Bench2Drive-mini/Accident_Town03_Route156_Weather0/lidar/xxxxx.laz**  only have the (x,y,z) coordinate.  In the file, it has already create the type of semantic_lidar but it seems not be storen in the dataset. Given that the semantic image is saved to the path normally, I'm confused because I didn't know where to get the semanticlidar data.

<img width="424" alt="b8ec7656b682c63e5791a88c393031f" src="https://github.com/user-attachments/assets/99e2f57c-d19f-4842-ba6b-088291b73614">

<img width="531" alt="af5dd409622ead883f00f080faf4769" src="https://github.com/user-attachments/assets/87c2a144-9d90-44ec-b683-f4ccbc50d2da">

So how can I get the semantic information of point cloud? Or may be I miss the semantic tag? Could you please offer me some advice? Because I have already seen that the code in data_collect.py .

If there is no better way to transform the tag to the point cloud,  I'd like to consult you that what kind of **"xxx.agent.py"** and which **route(.xml)** you had used for creating the dataset?  Would you please share with us so that we can add the semantic information to the dataset? And messages like your data_store rate, lidar position and other details will be appreciated.

**Comment by jayyoung0802** [comment]
I am sorry to inform you that our data does not contain lidar seg. Maybe you can add lidar sensor to collect your data by [carla_garage](https://github.com/autonomousvision/carla_garage/tree/leaderboard_2).
