### ISSUE TITLE
 time-out of 600000ms while waiting for the simulator

### ISSUE THREAD

**Issue by scuizhibin** [Thinklab-SJTU/Bench2Drive#68]
RuntimeError: time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30000,how to solver this error ?

**Comment by scuizhibin** [comment]
![image](https://github.com/user-attachments/assets/63814000-61de-4f82-b352-111d84234c58)

**Comment by scuizhibin** [comment]
运行了一段时间了，出现了这个问题 
![image](https://github.com/user-attachments/assets/a1fd5d0e-25e7-4251-804b-cb70049d9fb0)

**Comment by scuizhibin** [comment]
还是不行


---Original---
From: ***@***.***&gt;
Date: Tue, Aug 20, 2024 14:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive]  time-out of 600000ms while waitingfor the simulator (Issue #68)




 
@scuizhibin maybe you can try to set in time.sleep(120) in Bench2Drive/leaderboard/leaderboard/leaderboard_evaluator.py of "_setup_simulation" funtion.
 
&mdash;

**Comment by starlighttt123** [comment]
> RuntimeError: time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30000,how to solver this error ?

hello, have you solve this error? Btw, how to continue the eval process after this error? Simply re-run the bash files seems not right

**Comment by scuizhibin** [comment]
> > RuntimeError: time-out of 600000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:30000,how to solver this error ?
> 
> hello, have you solve this error? Btw, how to continue the eval process after this error? Simply re-run the bash files seems not right

I haven't solved this problem yet

**Comment by jiaxiaosong1002** [comment]
@scuizhibin @starlighttt123  Sleep longer. Clean CARLA. Try use less CARLA and python program in one single GPU. It is usually due to overwhelmed GPU and CPU, especially old ones.
