### ISSUE TITLE
mmcv version issue for closed-loop evaluation

### ISSUE THREAD

**Issue by Fengtao22** [Thinklab-SJTU/Bench2Drive#7]
Hi, thanks for providing the closed-loop evaluation platform. One question with respect to the mmcv package: I tried to directly test VAD repo using the Bench2Drive platform, however, the VAD requries mmdet (2.14.0) which needs a different version of mmcv. Hence, there are some incompatibility issues. 

For example, the mmdet checks mmcv version in its __init__.py will give "AssertionError: MMCV==0.0.1 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0." Even when I circulate this assert, I had another coming issue: AttributeError: module 'mmcv' has no attribute 'jit'.

Can you kindly provide some suggestions? Thanks!

**Comment by Fengtao22** [comment]
I just realized that the mmdet, mmcv and etc are merged into the mmcv folder and I should use the new config instead of the original VAD config. However, I still have issues in running the leaderboard. The current problem is:

in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by jayyoung0802** [comment]
Hi, thanks for your attention. In order to remove the restrictions on torch and cuda versions in the original uniad/vad repository, we have refactored the uniad/vad code. The repo is [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo). Please follow this link to install and evaluate.

**Comment by Fengtao22** [comment]
> Hi, thanks for your attention. In order to remove the restrictions on torch and cuda versions in the original uniad/vad repository, we have refactored the uniad/vad code. The repo is [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo). Please follow this link to install and evaluate.

Thanks for your quick reply! I actually did follow the Bench2DriveZoo to set up my environment. However, I still have the issue with GPUs. Any clue?

**Comment by Fengtao22** [comment]
> > Hi, thanks for your attention. In order to remove the restrictions on torch and cuda versions in the original uniad/vad repository, we have refactored the uniad/vad code. The repo is [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo). Please follow this link to install and evaluate.
> 
> Thanks for your quick reply! I actually did follow the Bench2DriveZoo to set up my environment. However, I still have the issue with GPUs. Any clue?

It turns out that I was using a wrong GPU_RANK for the bash file and after I changed it to 0 (for single GPU setting) it finally works!!!
