### ISSUE TITLE
请问闭环训练需要运行CarlaUE4.sh嘛，是只有闭环测试时需要嘛？

### ISSUE THREAD

**Issue by happytianhao** [Thinklab-SJTU/Bench2Drive#70]

**Comment by happytianhao** [comment]
此外，因为一些技术原因，我没办法在我跑实验的服务器上运行CarlaUE4.sh，只能在另一个小的服务器上运行Carla的服务端，想请问一下，在闭环模拟的过程中，CARLA的服务器端和客户端在不同的服务器上会影响速度嘛（训练or测试）

**Comment by jayyoung0802** [comment]
模仿学习所有的训练都是开环的
