### ISSUE TITLE
how to eval own method

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#71]
hello, we want to eval our own model in b2d, could you please give a more detailed tutorial of the organization structure of the `xx_agent.py` int teamcode ?  Thanks a lot

**Comment by jayyoung0802** [comment]
This it a [dummy agent](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/leaderboard/autoagents/dummy_agent.py). You need to fill in this format. Meanwhile, you can refer to ours uniad/vad/tcp/admlp agent in [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo/tree/uniad/vad/team_code).

**Comment by hollowknight2167** [comment]
> This it a [dummy agent](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/leaderboard/autoagents/dummy_agent.py). You need to fill in this format. Meanwhile, you can refer to ours uniad/vad/tcp/admlp agent in [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo/tree/uniad/vad/team_code).

Hello，may I ask you which `xx_agent.py` and `xxx.xml` did you use to collect the dataset, please? I am looking forward to collecting and adding the semantic_lidar data to the dataset.

**Comment by jayyoung0802** [comment]
@hollowknight2167 #67
