### ISSUE TITLE
请问这个耗时是正常的嘛，因为我测试的时候Carla服务器端和debug端不在同一个服务器上（内网），我担心数据传输会导致测试耗时过长。

### ISSUE THREAD

**Issue by happytianhao** [Thinklab-SJTU/Bench2Drive#73]
========= Results of RouteScenario_1711 (repetition 0) ------ SUCCESS =========

╒═══════════════════════╤═════════════════════╕
│ Start Time            │ 2024-08-22 17:19:31 │
├───────────────────────┼─────────────────────┤
│ End Time              │ 2024-08-22 17:30:27 │
├───────────────────────┼─────────────────────┤
│ System Time           │ 655.84s             │
├───────────────────────┼─────────────────────┤
│ Game Time             │ 24.9s               │
├───────────────────────┼─────────────────────┤
│ Ratio (Game / System) │ 0.038               │
╘═══════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤══════════╕
│ Criterion             │ Result  │ Value    │
├───────────────────────┼─────────┼──────────┤
│ RouteCompletionTest   │ SUCCESS │ 100 %    │
├───────────────────────┼─────────┼──────────┤
│ OutsideRouteLanesTest │ SUCCESS │ 0 %      │
├───────────────────────┼─────────┼──────────┤
│ CollisionTest         │ SUCCESS │ 0 times  │
├───────────────────────┼─────────┼──────────┤
│ RunningRedLightTest   │ SUCCESS │ 0 times  │
├───────────────────────┼─────────┼──────────┤
│ RunningStopTest       │ SUCCESS │ 0 times  │
├───────────────────────┼─────────┼──────────┤
│ MinSpeedTest          │ SUCCESS │ 117.29 % │
├───────────────────────┼─────────┼──────────┤
│ InRouteTest           │ SUCCESS │          │
├───────────────────────┼─────────┼──────────┤
│ AgentBlockedTest      │ SUCCESS │          │
├───────────────────────┼─────────┼──────────┤
│ Timeout               │ SUCCESS │          │
╘═══════════════════════╧═════════╧══════════╛

**Comment by jayyoung0802** [comment]
That's right.
