### ISSUE TITLE
Bench2DriveZoo Integration

### ISSUE THREAD

**Issue by ymoghadd** [Thinklab-SJTU/Bench2Drive#74]
I'm trying to do a closed-loop evaluation for UniAD. I have set up the carla environment, but obviously Bench2DriveZoo has its own environment with some packages that conflict with the carla environment. Not to mention, the leaderboard 2.0 page said to install python 3.7 for the carla environment, while Bench2DriveZoo uses python 3.8. That's just one example. Will you make documentation to address this issue? The carla environment is fine, but now I have to manually install all the Bench2DriveZoo packages, since Bench2DriveZoo itself does not contain packages for carla.

**Comment by jayyoung0802** [comment]
carla-0.9.15-py3.7-linux-x86_64.egg  works well in py38, It can be used normally. Please refer to [setup](https://github.com/Thinklab-SJTU/Bench2Drive?tab=readme-ov-file#setup)
