### ISSUE TITLE
scenario could not be loaded 

### ISSUE THREAD

**Issue by scuizhibin** [Thinklab-SJTU/Bench2Drive#76]
my machine ：RTX3090 ，Computer memory  32G  

![image](https://github.com/user-attachments/assets/a5a899fc-7007-4827-88d4-fb72c1d8aa83)

**Comment by jayyoung0802** [comment]
Carla crashed before load scenario. Make sure your carla works well.

**Comment by scuizhibin** [comment]
it&nbsp;work&nbsp;well


---Original---
From: ***@***.***&gt;
Date: Mon, Aug 26, 2024 12:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] scenario could not be loaded  (Issue#76)




 
Carla crashed before load scenario. Make sure your carla works well.

**Comment by jayyoung0802** [comment]
See #32

**Comment by scuizhibin** [comment]
如何减少task的数目&nbsp;，你知道吗？


---Original---
From: ***@***.***&gt;
Date: Mon, Aug 26, 2024 12:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] scenario could not be loaded  (Issue#76)




 
See #32
 
&mdash;

**Comment by jayyoung0802** [comment]
https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation_multi_uniad.sh#L25

**Comment by scuizhibin** [comment]
我用的只是这个debug&nbsp;的&nbsp;&nbsp;单显卡的类型。结果出下signal=11这个问题。，请问大佬使用的显卡和内存是多少


---Original---
From: ***@***.***&gt;
Date: Mon, Aug 26, 2024 13:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] scenario could not be loaded  (Issue#76)




 
https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation_multi_uniad.sh#L25
 
&mdash;

**Comment by jayyoung0802** [comment]
We use 3090(24G), A6000(48G) or H800(80G).  All work well. Your memory 32G may be a limitation. Could you try anothor machine?

**Comment by scuizhibin** [comment]
服务器&nbsp;我也试过，3090的&nbsp;服务器，128g也会出现这个问题。&nbsp;服务器的显卡驱动是535。


---Original---
From: ***@***.***&gt;
Date: Mon, Aug 26, 2024 14:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Thinklab-SJTU/Bench2Drive] scenario could not be loaded  (Issue#76)




 
We use 3090(24G), A6000(48G) or H800(80G).  All work well. Your memory 32G may be a limitation. Could you try anothor machine?
 
&mdash;

**Comment by jiaxiaosong1002** [comment]
@scuizhibin Sleep longer. Clean CARLA. Try use less CARLA and python program in one single GPU. It is usually due to overwhelmed GPU and CPU, especially old ones.
