### ISSUE TITLE
Cannot Spawn Actor

### ISSUE THREAD

**Issue by ymoghadd** [Thinklab-SJTU/Bench2Drive#78]
I keep having this error when I try to run either UniAD or VAD:

=== [Agent] -- Wallclock = 2024-08-26 15:51:33.428 -- System time = 21.707 -- Game time = 1.800 -- Ratio = 0.083x
WARNING: Cannot spawn actor vehicle.* at position Location(x=2773.693604, y=1783.304810, z=346.687805)
=== [Agent] -- Wallclock = 2024-08-26 15:51:33.978 -- System time = 22.257 -- Game time = 1.850 -- Ratio = 0.083x
WARNING: Cannot spawn actor vehicle.* at position Location(x=277

And it keeps repeating unless I do Ctrl-C, after which it constantly displays something like the following:
=== [Agent] -- Wallclock = 2024-08-26 15:53:18.503 -- System time = 1008.673 -- Game time = 58.200 -- Ratio = 0.058x

How must I resolve this issue? I'm guessing it may have to do with an actor being spawned and there immediately being a crash.

**Comment by jayyoung0802** [comment]
This is a normal display， and warning can be ignored.
