### ISSUE TITLE
Log Replay and Metric Computation for Bench2Drive Datasets

### ISSUE THREAD

**Issue by huangzehao** [Thinklab-SJTU/Bench2Drive#79]
Hi Bench2Drive Developers,
Thank you for your excellent work on the Bench2Drive benchmark.

I understand that the Bench2Drive benchmark contains three subset datasets: Mini, Base, and Full. I have a question regarding log replay and metric computation:
Is there a method to perform log replay using the provided datasets and obtain corresponding metrics? I assume we would need the route XML files and agent logs to conduct log replay and compute metrics. Could you please confirm if this is correct, and if so, provide any guidance on how to proceed?

If any of my assumptions or statements above are incorrect, I would greatly appreciate your corrections and clarifications.

Your guidance and explanations would be extremely helpful. Thank you for your time and assistance.

**Comment by jiaxiaosong1002** [comment]
@huangzehao We use the in-house expert Think2Drive. You may try with PDM-Lite: https://github.com/autonomousvision/carla_garage/tree/leaderboard_2.
