### ISSUE TITLE
how do i run this model?

### ISSUE THREAD

**Issue by chrissunny94** [Thinklab-SJTU/Bench2Drive#8]
I am trying to run the CARLA pipeline for testing the End to End Closed loop evaluation pipeline .

Kindly let me know how to execute this .

**Comment by jayyoung0802** [comment]
Hi, Thanks for your question. You can follow this [EVAL Doc,](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/EVAL_IN_CARLA.md) , Our code and ckpts also can be found in repo [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo).
