### ISSUE TITLE
Log Video Replay Shows Stationary Ego Vehicle

### ISSUE THREAD

**Issue by ymoghadd** [Thinklab-SJTU/Bench2Drive#80]
When I replay the log video by doing client.replay_file('log_file.log', 0,0,0), it shows a BEV of an intersection, with cars moving but quickly disappearing. It does not follow an ego vehicle's trajectory. In fact, what I presume to be the ego vehicle does not even move. This happens when I evaluate vad_b2d_base.pth. Why is this and how can I resolve this issue?

**Comment by jiaxiaosong1002** [comment]
@ymoghadd  https://github.com/Thinklab-SJTU/Bench2Drive/issues/31
