### ISSUE TITLE
This route does not contain any junction-waypoint

### ISSUE THREAD

**Issue by swc-17** [Thinklab-SJTU/Bench2Drive#83]
The error below raised when evaluating multi-ability, why is junction-waypoint necessary? Can I just comment out line 136-137?
```
Traceback (most recent call last):
  File "close_loop/tools/ability_benchmark.py", line 181, in <module>
    main(args)
  File "close_loop/tools/ability_benchmark.py", line 137, in main
    raise RuntimeError("This route does not contain any junction-waypoint!")
RuntimeError: This route does not contain any junction-waypoint!
```

**Comment by jayyoung0802** [comment]
Hi, Please provide the route id.

**Comment by swc-17** [comment]
We re-evaluated and did not encounter the same error, did not know why.

**Comment by MrPicklesGG** [comment]
This may be caused by the map not being fully loaded.
You can add `time.sleep(15)` after line 125 `world = client.load_world(current_town)` in the tools/ability_benchmark.py
