### ISSUE TITLE
Closed Loop Visualization of Planned Trajectory / Detected Objects

### ISSUE THREAD

**Issue by julien-seitz** [Thinklab-SJTU/Bench2Drive#87]
Hello, thanks much for your very nice repository.
I got some models successfully working in the closed loop simulation.
I also have the output images and can generate the videos via generate_video.py

However I would be very much interested in generating some videos that do contain the planned trajectory as well as the detected bounding boxes like in here:
https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/analysis/analysis.md#merging

As far as I know, the tools/visualize.py file is only for visualizing a B2D dataset and not for visualizing a closed loop simulation.
Do you know where I could find such a script?

Thanks much

**Comment by zhiyuanzzz** [comment]
Thanks for your question! We have updated the visualization code of VAD at https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/team_code/vad_b2d_agent_visualize.py. You can refer to it to do visualization of other models.
