### ISSUE TITLE
Where is command_near derived from?

### ISSUE THREAD

**Issue by Fengtao22** [Thinklab-SJTU/Bench2Drive#9]
Hi, I tried to directly test VAD ckpt using the Bench2Drive platform but had the issue about the driving command index out of range. The cause was due to the number of commands used in the original VAD is 3 but here the number is 6. 

Could you please kindly explain where the command_near is derived (gt command I believe?) and also what are the corresponding commands for the one-hot vector (dimension is 6)? Thanks in advance!!

**Comment by jiaxiaosong1002** [comment]
@Fengtao22 Hi, you may not directly do that.  Many hyper-parameters are specifically for CARLA, for example, high-level command and object detection classes.  

Command_near is the nearest routing waypoint provided by CARLA and the actual meaning of one-hot vector:
# VOID = -1
  # LEFT = 1
  # RIGHT = 2
  # STRAIGHT = 3
  # LANEFOLLOW = 4
  # CHANGELANELEFT = 5
  # CHANGELANERIGHT = 6
which is definied by CARLA official team as well.

**Comment by Fengtao22** [comment]
Thanks for your quick reply!
