### ISSUE TITLE
Ques about some test data

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#92]
Hello, In `RouteScenario_11715_rep0_Town12`, there are two cars in front of the ego car  suddenly disappear in the beginning of the video, which dosen't seem reasonable, is it a simply a bug or it's selected deliberately？

Thanks for your reply!

https://github.com/user-attachments/assets/3df2da36-cfb4-4825-a563-03a171d5d1ed

**Comment by jayyoung0802** [comment]
Please refer to #3 and #31.
