### ISSUE TITLE
Ego vehicle with no Vehicles in environment

### ISSUE THREAD

**Issue by ymoghadd** [Thinklab-SJTU/Bench2Drive#93]
Hi,
How would I have the models running with only the ego vehicle and no other vehicles in the environment? I just want to see how the model performs with no adversaries.

**Comment by jayyoung0802** [comment]
You can select **NoScenario** route from the dataset and eval it.

**Comment by ymoghadd** [comment]
Where do I select NoScenario?

**Comment by jayyoung0802** [comment]
There are in [Bench2Drive Full](https://huggingface.co/datasets/rethinklab/Bench2Drive-Full/tree/main).

**Comment by ymoghadd** [comment]
I see. Thank you for your response.
