### ISSUE TITLE
Scaling Law Curve

### ISSUE THREAD

**Issue by YangS03** [Thinklab-SJTU/Bench2Drive#95]
I am wondering if you test the scaling law curve when you increase the training dataset since you have released different datasets with different sizes. You choose 1K routes for full-setting and claim that it's comparable to Nuscenes. But Nuscenes is not for training an agent but was developed for an autonomous driving perception system. Could you be so kind as to try to draw the curve using different amounts of data since it consumes a lot of resources to reproduce the result independently?

**Comment by jiaxiaosong1002** [comment]
@YangS03 You may do it by yourself.
