### ISSUE TITLE
Question about collecting expert data

### ISSUE THREAD

**Issue by Kaiwen-Hong** [Thinklab-SJTU/Bench2Drive#96]
Thanks the authors for sharing the marvelous work! You mentioned we can collect data using the expert RL agent and referred to tools/data_collect.py. However, how can we directly use this script? Could you kindly add some explanations or commands to collect data?

**Comment by jiaxiaosong1002** [comment]
@Kaiwen-Hong Please check https://github.com/Thinklab-SJTU/Bench2Drive/issues/26.
