### ISSUE TITLE
如何保证我运行的仿真场景中的交通流和开源数据集中的交通流一致？

### ISSUE THREAD

**Issue by array-svg** [Thinklab-SJTU/Bench2Drive#98]
我在本地加载开源的xml剧本，然后设置和数据集相同的随机种子(42)，其他的设置保持默认, 是否可以严格保证我运行的仿真场景中的交通流能够和开源数据集中的交通流一致？

**Comment by jayyoung0802** [comment]
No, there is randomness in carla, and the other vehicles are reactive by agent's behavior.
