### ISSUE TITLE
where find python requirement

### ISSUE THREAD

**Issue by lightning0016** [Thinklab-SJTU/Bench2Drive#99]
i had down and installed carla,but not run.where can find torch version,tensorflow version and others requirement

**Comment by jayyoung0802** [comment]
@lightning0016, Carla don't need torch/tf.
If you want to run some End2End autonomous driving algo such as VAD/UniAD, just follow [Bench2DriveZoo](https://github.com/Thinklab-SJTU/Bench2DriveZoo)
